from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

VERSAO_INVENTARIO_LEGADO_PIPELINE = 'ME-518A'
ARTEFATO_INVENTARIO_LEGADO_PIPELINE = 'InventarioLegadoPipeline'
FONTE_INVENTARIO = 'inventario_estatico_declarativo_versionado'
REMOCAO_AUTOMATICA_AUTORIZADA = False

CLASSIFICACOES_PADRONIZADAS = (
    'rota_oficial_preservada',
    'legado_candidato_depreciacao',
    'bloqueado_dependencia_ativa',
    'historico_preservado',
    'diagnostico_preservado_fora_pipeline',
    'fallback_temporario_bloqueado_para_remocao',
    'avaliacao_remocao_futura',
)


@dataclass(frozen=True, slots=True)
class ItemInventarioLegadoPipeline:
    identificador: str
    arquivo: str
    simbolo_funcao_classe: str
    camada: str
    tipo: str
    uso_atual: str
    dependencia_ativa: bool
    substituto_oficial: str
    risco_operacional: str
    decisao_recomendada: str
    etapa_alvo_tratamento: str
    evidencia: str
    justificativa_de_classificacao: str
    classificacao: str
    remocao_automatica_autorizada: bool = REMOCAO_AUTOMATICA_AUTORIZADA

    def como_dict(self) -> dict[str, Any]:
        return asdict(self)


def _item(
    identificador: str,
    arquivo: str,
    simbolo: str,
    camada: str,
    tipo: str,
    uso: str,
    dependencia: bool,
    substituto: str,
    risco: str,
    decisao: str,
    alvo: str,
    evidencia: str,
    justificativa: str,
    classificacao: str,
) -> ItemInventarioLegadoPipeline:
    return ItemInventarioLegadoPipeline(
        identificador=identificador,
        arquivo=arquivo,
        simbolo_funcao_classe=simbolo,
        camada=camada,
        tipo=tipo,
        uso_atual=uso,
        dependencia_ativa=dependencia,
        substituto_oficial=substituto,
        risco_operacional=risco,
        decisao_recomendada=decisao,
        etapa_alvo_tratamento=alvo,
        evidencia=evidencia,
        justificativa_de_classificacao=justificativa,
        classificacao=classificacao,
    )


ITENS_INVENTARIO_LEGADO_PIPELINE: tuple[ItemInventarioLegadoPipeline, ...] = (
    _item(
        'OFICIAL-PRINCIPAL-01',
        'aplicacao/principal.py',
        'main; carregar_contexto_e_saida',
        'aplicacao',
        'rota_oficial',
        'Entrada operacional integrada que executa cadeia validada, console, XLSX, Etapa 10 e Etapa 11.',
        False,
        'nao_aplicavel_rota_oficial',
        'alto_se_removida_por_ser_ponto_de_entrada_oficial',
        'preservar_integralmente',
        'Etapa 11 - preservacao',
        'A rota integrada entrega PacoteSaidaObservavelOficial para console e XLSX oficiais.',
        'Rota oficial não é resíduo; deve ser separada de legado executável.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-SAIDA-OBSERVAVEL-09-01',
        'nucleo/saida_observavel_oficial.py',
        'construir_pacote_saida_observavel_oficial',
        'nucleo/saida_oficial',
        'pacote_oficial_etapa9',
        'Materializa PacoteSaidaObservavelOficial consumido por console, XLSX e Etapa 10.',
        False,
        'nao_aplicavel_rota_oficial',
        'alto_se_confundido_com_pacote_temporal_legado',
        'preservar_como_substituto_oficial_dos_helpers_observaveis_antigos',
        'Etapa 9 - preservacao',
        'Pacote oficial é entrada da paridade forte da Etapa 10.',
        'É o substituto oficial contra o qual resíduos observáveis devem ser comparados.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-CONSOLE-09-10-ME518A',
        'aplicacao/console/principal.py',
        'render_console',
        'aplicacao/console',
        'rota_observavel_oficial',
        'Renderiza exclusivamente PacoteSaidaObservavelOficial preparado; sem reconstrução V17/C7, S7B/S7C ou pacote temporal.',
        False,
        'PacoteSaidaObservavelOficial recebido da rota integrada',
        'alto_se_reintroduzir_fallback_de_renderizacao',
        'preservar_rota_oficial_sem_fallback',
        'ME-518A - preservacao da rota refatorada',
        'Console oficial falha explicitamente quando PacoteSaidaObservavelOficial não é fornecido ou não está preparado.',
        'A rota de console foi refatorada para consumir apenas a fonte observável oficial.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-XLSX-09-10-ME518A',
        'nucleo/gerar_planilha_operacional.py',
        'main',
        'nucleo/xlsx',
        'rota_observavel_oficial',
        'Gera as abas oficiais exclusivamente a partir de bloco_xlsx do PacoteSaidaObservavelOficial completo.',
        False,
        'bloco_xlsx.abas e bloco_xlsx.situacao_atual_blocos',
        'alto_se_reintroduzir_fallback_xlsx_sem_pacote_oficial',
        'preservar_rota_xlsx_oficial_sem_fallback',
        'ME-518A - preservacao da rota refatorada',
        'Geração XLSX oficial valida pacote preparado e recusa abas obrigatórias ausentes.',
        'A planilha oficial passa a ser renderização do pacote oficial, não reconstrução alternativa.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-ETAPA11-01',
        'nucleo/limpeza_depreciacao_controlada.py',
        'construir_resultado_limpeza_depreciacao_controlada',
        'nucleo/governanca',
        'etapa_governanca_nao_decisoria',
        'Classifica evidências auxiliares sem reabrir motor, ledger, gates, Etapa 9 ou Etapa 10.',
        False,
        'ResultadoParidadeRenderizacaoOficial continua sendo entrada formal obrigatoria',
        'alto_se_inventario_for_usado_como_entrada_decisoria',
        'preservar_sem_autorizar_remocao_automatica',
        'Etapa 11 - preservacao',
        'Contrato da Etapa 11 exige ResultadoParidadeRenderizacaoOficial como entrada formal.',
        'A Etapa 11 apenas recebe inventário como evidência auxiliar não decisória.',
        'rota_oficial_preservada',
    ),
    _item(
        'PACOTE-OBS-TEMPORAL-MODULO-01',
        'nucleo/pacote_saida_observavel_temporal.py',
        'PacoteSaidaObservavelTemporal; construir_pacote_saida_observavel_temporal',
        'nucleo/saida_observavel_transitoria',
        'pacote_temporal_transitorio',
        'Permanece existente na montagem transitória anterior ao pacote oficial; não é mais consumido diretamente por console ou XLSX oficiais.',
        True,
        'PacoteSaidaObservavelOficial para rotas observáveis de console e XLSX',
        'alto_se_removido_antes_de_migrar_a_montagem_transitoria_da_rota_integrada',
        'bloquear_remocao_fora_do_escopo_console_xlsx',
        'ME posterior de migração da montagem oficial',
        'aplicacao/principal.py ainda monta Situação Atual antes da saída oficial; ME-518A não altera principal.',
        'ME-518A remove consumo em console/XLSX, mas não altera a cadeia anterior ao pacote oficial.',
        'bloqueado_dependencia_ativa',
    ),
    _item(
        'SAIDA-OBS-CONSOLIDA-LOTES-01',
        'nucleo/saida_observavel.py',
        'construir_linhas_lotes_consolidados',
        'nucleo/renderizacao_observavel_legada',
        'helper_observavel_ativo',
        'Não é mais chamado por console/XLSX oficiais; pode permanecer ativo na montagem transitória pré-pacote.',
        True,
        'blocos de lotes do PacoteSaidaObservavelOficial nas rotas de renderização',
        'alto_por_afetar_montagem_previa_da_saida_oficial_se_removido_agora',
        'bloquear_remocao_fora_do_escopo_console_xlsx',
        'ME posterior de migração da montagem da Situação Atual',
        'Removido de aplicacao/console/principal.py e nucleo/gerar_planilha_operacional.py.',
        'A dependência ativa restante está fora do escopo de console/XLSX desta ME.',
        'bloqueado_dependencia_ativa',
    ),
    _item(
        'SAIDA-OBS-AMOSTRAS-PAGAMENTOS-01',
        'nucleo/saida_observavel.py',
        'construir_amostras_pagamentos_operacionais',
        'nucleo/renderizacao_observavel_legada',
        'helper_console_fallback',
        'Removido da rota operacional do console; amostras passam a vir de bloco_console do PacoteSaidaObservavelOficial.',
        False,
        'bloco_console.ultimos_pagamentos; bloco_console.pagamentos_data_referencia; bloco_console.proximos_pagamentos',
        'baixo_na_rota_oficial_apos_me518a; medio_se_chamado_manualmente_fora_da_rota_integrada',
        'avaliar_depreciacao_futura_sem_remocao_automatica',
        'ME posterior de limpeza de helpers não consumidos',
        'Import e chamada removidos de aplicacao/console/principal.py.',
        'Sem consumo operacional em console/XLSX, torna-se candidato de depreciação futura, sem remoção automática.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'SAIDA-OBS-SITUACAO-ATUAL-HELPERS-01',
        'nucleo/saida_observavel.py',
        'construir_linhas_lotes_id_curta; construir_linhas_lotes_valores_curta; construir_resumo_patrimonio_total_lotes; construir_blocos_situacao_atual',
        'nucleo/renderizacao_observavel_legada',
        'helpers_situacao_atual',
        'Não são mais chamados por console/XLSX oficiais; podem participar da montagem transitória anterior à criação do pacote oficial.',
        True,
        'situacao_atual_* em bloco_console e situacao_atual_blocos em bloco_xlsx',
        'alto_se_removidos_antes_de_substituir_a_montagem_previa_da_saida_oficial',
        'bloquear_remocao_fora_do_escopo_console_xlsx',
        'ME posterior de migração da montagem da Situação Atual',
        'Fallbacks de renderização removidos de console/XLSX; montagem pré-pacote permanece fora do escopo autorizado.',
        'ME-518A trata consumidores de renderização, não a montagem transitória da origem de Situação Atual.',
        'bloqueado_dependencia_ativa',
    ),
    _item(
        'CONSOLE-STANDALONE-V17-S7-01',
        'aplicacao/console/principal.py',
        'main; render_console sem pacote oficial',
        'aplicacao/console',
        'fallback_console_standalone_removido',
        'Standalone não reconstrói mais V17/C7, matriz S7B ou integração S7C; falha explicitamente sem pacote oficial.',
        False,
        'aplicacao/principal.py com PacoteSaidaObservavelOficial preparado',
        'baixo_na_rota_oficial_apos_me518a; alto_se_reintroduzido',
        'preservar_falha_explicita_e_nao_reintroduzir_fallback',
        'ME-518A concluida para console',
        'main() do console chama render_console sem pacote apenas para produzir falha contratual explícita.',
        'Fallback executável foi removido da rota de console sem alterar decisão econômica.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'CONSOLE-SITUACAO-ANTIGA-01',
        'aplicacao/console/principal.py',
        'fallback antigo de Situação Atual',
        'aplicacao/console',
        'fallback_console_situacao_atual_removido',
        'Console renderiza Situação Atual exclusivamente a partir de bloco_console do PacoteSaidaObservavelOficial.',
        False,
        'bloco_console.situacao_atual_*',
        'baixo_na_rota_oficial_apos_me518a; alto_se_reintroduzido',
        'preservar_rota_oficial_sem_fallback',
        'ME-518A concluida para console',
        'Rota else antiga foi removida; ausência de pacote oficial gera erro explícito.',
        'A renderização observável não consulta mais helpers antigos para completar Situação Atual.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'CONSOLE-AMOSTRAS-FALLBACK-01',
        'aplicacao/console/principal.py',
        'fallback antigo de amostras de pagamentos',
        'aplicacao/console',
        'fallback_console_pagamentos_removido',
        'Console usa somente listas oficiais de pagamentos do bloco_console.',
        False,
        'bloco_console.ultimos_pagamentos; bloco_console.pagamentos_data_referencia; bloco_console.proximos_pagamentos',
        'baixo_na_rota_oficial_apos_me518a; medio_se_reintroduzido',
        'preservar_rota_oficial_sem_fallback',
        'ME-518A concluida para console',
        'Import e chamada do helper de amostras foram removidos do console.',
        'Amostras passam a ser renderização do pacote oficial, não reconstrução local.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'XLSX-FALLBACK-BLOQUEADO-01',
        'nucleo/gerar_planilha_operacional.py',
        'main; rotas de geração sem pacote oficial',
        'nucleo/xlsx',
        'fallback_xlsx_removido',
        'XLSX oficial recusa execução sem PacoteSaidaObservavelOficial preparado e abas oficiais completas.',
        False,
        'bloco_xlsx.abas e bloco_xlsx.situacao_atual_blocos',
        'baixo_na_rota_oficial_apos_me518a; alto_se_reintroduzido',
        'preservar_rota_xlsx_oficial_sem_fallback',
        'ME-518A concluida para XLSX',
        'Imports e chamadas de reconstrução temporal/observável foram removidos do gerador XLSX.',
        'Planilha oficial deixa de reconstruir conteúdo alternativo quando pacote oficial existe.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'SAIDA-CANONICA-V17-C7-01',
        'nucleo/construir_saida_canonica_v17_c7.py',
        'construir_saida_canonica_com_switching_v17_c7',
        'nucleo/saida_canonica_legada',
        'wrapper_legado_ativo',
        'Não é mais chamado por console/XLSX oficiais; permanece na rota integrada anterior à materialização da saída oficial.',
        True,
        'nucleo.saida_canonica_oficial.construir_saida_canonica_oficial',
        'alto_se_removido_antes_de_migrar_fontes_de_saida_canonica_antiga_na_rota_integrada',
        'bloquear_remocao_fora_do_escopo_console_xlsx',
        'ME posterior de substituição da montagem de saída canônica antiga',
        'Escopo ME-518A proíbe alterar aplicacao/principal.py.',
        'Remoção de consumidores de renderização não equivale a remoção da montagem transitória anterior.',
        'bloqueado_dependencia_ativa',
    ),
    _item(
        'MATRIZ-S7B-S7C-01',
        'nucleo/matriz_elegibilidade_fontes_s7b.py; nucleo/integracao_matriz_elegibilidade_pagamentos_s7c.py',
        'construir_matriz_elegibilidade_fontes_s7b; aplicar_matriz_elegibilidade_ao_fluxo_pagamentos_s7c',
        'nucleo/elegibilidade_legada_transitoria',
        'matriz_integracao_transitoria_ativa',
        'Não são mais chamadas por console/XLSX oficiais; permanecem fora do escopo desta ME enquanto a rota integrada ainda as utiliza.',
        True,
        'cadeia oficial motor/ledger/gates e obrigações cobertas no PacoteSaidaObservavelOficial',
        'alto_se_removidas_sem_substituir_fluxo_transitorio_da_rota_integrada',
        'bloquear_remocao_fora_do_escopo_console_xlsx',
        'ME posterior de migração de elegibilidade transitória',
        'Escopo ME-518A restringe a remoção aos consumidores de console/XLSX.',
        'Matriz e integração seguem inventariadas como dependência ativa fora do escopo de renderização.',
        'bloqueado_dependencia_ativa',
    ),
    _item(
        'CODE-OTIMIZACAO-GASTOS-01',
        'code/otimizacao_gastos.py',
        'modulo code/otimizacao_gastos.py',
        'code/referencia_historica_fora_pipeline',
        'referencia_historica_preservada',
        'Referência histórica preservada integralmente fora do pipeline operacional atual.',
        False,
        'nao_aplicavel_por_preservacao_historica_integral',
        'alto_para_rastreabilidade_se_removido_ou_modificado; baixo_para_runtime_oficial_enquanto_nao_importado_pelo_pipeline',
        'preservar_integralmente_sem_mover_converter_substituir_ou_remover',
        'fora_do_pipeline_runtime_preservacao_historica',
        'ME-517 reclassificou code/ como referência histórica fora do pipeline.',
        'code/ permanece integralmente preservado e fora do escopo da ME-518A.',
        'historico_preservado',
    ),
    _item(
        'CODE-OTIMIZACAO-SWTICHING-01',
        'code/otimizacao_swtiching.py',
        'modulo code/otimizacao_swtiching.py',
        'code/referencia_historica_fora_pipeline',
        'referencia_historica_preservada',
        'Referência histórica de switching preservada integralmente fora do pipeline operacional atual; grafia swtiching preservada por ser nome de arquivo existente.',
        False,
        'nao_aplicavel_por_preservacao_historica_integral',
        'alto_para_rastreabilidade_se_removido_ou_modificado; baixo_para_runtime_oficial_enquanto_nao_importado_pelo_pipeline',
        'preservar_integralmente_sem_mover_converter_substituir_ou_remover',
        'fora_do_pipeline_runtime_preservacao_historica',
        'ME-517 reclassificou code/ como referência histórica fora do pipeline.',
        'code/ permanece integralmente preservado e fora do escopo da ME-518A.',
        'historico_preservado',
    ),
)


def listar_itens_inventario_legado_pipeline() -> list[dict[str, Any]]:
    return [item.como_dict() for item in ITENS_INVENTARIO_LEGADO_PIPELINE]


def construir_inventario_legado_pipeline() -> dict[str, Any]:
    return {
        'artefato': ARTEFATO_INVENTARIO_LEGADO_PIPELINE,
        'versao': VERSAO_INVENTARIO_LEGADO_PIPELINE,
        'fonte': FONTE_INVENTARIO,
        'natureza': 'evidencia_auxiliar_nao_decisoria',
        'estatico_declarativo_versionado': True,
        'usa_varredura_dinamica_filesystem': False,
        'entrada_formal_etapa11': 'ResultadoParidadeRenderizacaoOficial',
        'substitui_resultado_paridade_renderizacao_oficial': False,
        'remocao_automatica_autorizada': REMOCAO_AUTOMATICA_AUTORIZADA,
        'classificacoes_padronizadas': list(CLASSIFICACOES_PADRONIZADAS),
        'regras_contratuais': {
            'inventario_nao_decisorio': True,
            'nao_corrige_paridade': True,
            'nao_reabre_motor': True,
            'nao_reabre_ledger': True,
            'nao_reabre_gates': True,
            'nao_altera_etapa9': True,
            'nao_altera_etapa10': True,
            'nao_autoriza_remocao_automatica': True,
            'itens_com_dependencia_ativa_bloqueados_para_remocao': True,
            'me518a_limitada_a_console_xlsx': True,
            'code_preservado_integralmente': True,
        },
        'itens': listar_itens_inventario_legado_pipeline(),
    }
