from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

VERSAO_INVENTARIO_LEGADO_PIPELINE = 'ME-518C'
ARTEFATO_INVENTARIO_LEGADO_PIPELINE = 'InventarioLegadoPipeline'
FONTE_INVENTARIO = 'inventario_estatico_declarativo_versionado'
REMOCAO_AUTOMATICA_AUTORIZADA = False

CLASSIFICACOES_PADRONIZADAS = (
    'rota_oficial_preservada',
    'legado_candidato_depreciacao',
    'legado_removido',
    'bloqueado_dependencia_ativa',
    'historico_preservado',
    'diagnostico_preservado_fora_pipeline',
    'fallback_temporario_bloqueado_para_remocao',
    'avaliacao_remocao_futura',
)


@dataclass(frozen=True, slots=True)
class ItemInventarioLegadoPipeline:
    identificador: str
    arquivo: str
    simbolo_funcao_classe: str
    camada: str
    tipo: str
    uso_atual: str
    dependencia_ativa: bool
    substituto_oficial: str
    risco_operacional: str
    decisao_recomendada: str
    etapa_alvo_tratamento: str
    evidencia: str
    justificativa_de_classificacao: str
    classificacao: str
    remocao_automatica_autorizada: bool = REMOCAO_AUTOMATICA_AUTORIZADA

    def como_dict(self) -> dict[str, Any]:
        return asdict(self)


def _item(
    identificador: str,
    arquivo: str,
    simbolo: str,
    camada: str,
    tipo: str,
    uso: str,
    dependencia: bool,
    substituto: str,
    risco: str,
    decisao: str,
    alvo: str,
    evidencia: str,
    justificativa: str,
    classificacao: str,
) -> ItemInventarioLegadoPipeline:
    return ItemInventarioLegadoPipeline(
        identificador=identificador,
        arquivo=arquivo,
        simbolo_funcao_classe=simbolo,
        camada=camada,
        tipo=tipo,
        uso_atual=uso,
        dependencia_ativa=dependencia,
        substituto_oficial=substituto,
        risco_operacional=risco,
        decisao_recomendada=decisao,
        etapa_alvo_tratamento=alvo,
        evidencia=evidencia,
        justificativa_de_classificacao=justificativa,
        classificacao=classificacao,
    )


ITENS_INVENTARIO_LEGADO_PIPELINE: tuple[ItemInventarioLegadoPipeline, ...] = (
    _item(
        'OFICIAL-PRINCIPAL-01',
        'aplicacao/principal.py',
        'main; carregar_contexto_e_saida',
        'aplicacao',
        'rota_oficial',
        'Entrada operacional integrada que executa cadeia validada, console, XLSX, Etapa 10 e Etapa 11 sem consumir V17/C7, S7B ou S7C.',
        False,
        'nao_aplicavel_rota_oficial',
        'alto_se_removida_por_ser_ponto_de_entrada_oficial',
        'preservar_integralmente',
        'Etapa 11 - preservacao',
        'A rota integrada entrega PacoteSaidaObservavelOficial para console e XLSX oficiais a partir de ResultadoMotorTemporalConjunto, LedgerTemporalCanonico e ResultadoGatesValidacaoNucleo.',
        'Rota oficial não é resíduo; deve ser separada de legado executável.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-SAIDA-OBSERVAVEL-09-01',
        'nucleo/saida_observavel_oficial.py',
        'construir_pacote_saida_observavel_oficial',
        'nucleo/saida_oficial',
        'pacote_oficial_etapa9',
        'Materializa PacoteSaidaObservavelOficial consumido por console, XLSX e Etapa 10.',
        False,
        'nao_aplicavel_rota_oficial',
        'alto_se_confundido_com_pacote_temporal_legado',
        'preservar_como_substituto_oficial_dos_helpers_observaveis_antigos',
        'Etapa 9 - preservacao',
        'Pacote oficial é entrada da paridade forte da Etapa 10.',
        'É o substituto oficial contra o qual resíduos observáveis devem ser comparados.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-CONSOLE-09-10-ME518A',
        'aplicacao/console/principal.py',
        'render_console',
        'aplicacao/console',
        'rota_observavel_oficial',
        'Renderiza exclusivamente PacoteSaidaObservavelOficial preparado; sem reconstrução V17/C7, S7B/S7C ou pacote temporal.',
        False,
        'PacoteSaidaObservavelOficial recebido da rota integrada',
        'alto_se_reintroduzir_fallback_de_renderizacao',
        'preservar_rota_oficial_sem_fallback',
        'ME-518A - preservacao da rota refatorada',
        'Console oficial falha explicitamente quando PacoteSaidaObservavelOficial não é fornecido ou não está preparado.',
        'A rota de console foi refatorada para consumir apenas a fonte observável oficial.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-XLSX-09-10-ME518A',
        'nucleo/gerar_planilha_operacional.py',
        'main',
        'nucleo/xlsx',
        'rota_observavel_oficial',
        'Gera as abas oficiais exclusivamente a partir de bloco_xlsx do PacoteSaidaObservavelOficial completo.',
        False,
        'bloco_xlsx.abas e bloco_xlsx.situacao_atual_blocos',
        'alto_se_reintroduzir_fallback_xlsx_sem_pacote_oficial',
        'preservar_rota_xlsx_oficial_sem_fallback',
        'ME-518A - preservacao da rota refatorada',
        'Geração XLSX oficial valida pacote preparado e recusa abas obrigatórias ausentes.',
        'A planilha oficial passa a ser renderização do pacote oficial, não reconstrução alternativa.',
        'rota_oficial_preservada',
    ),
    _item(
        'OFICIAL-ETAPA11-01',
        'nucleo/limpeza_depreciacao_controlada.py',
        'construir_resultado_limpeza_depreciacao_controlada',
        'nucleo/governanca',
        'etapa_governanca_nao_decisoria',
        'Classifica evidências auxiliares sem reabrir motor, ledger, gates, Etapa 9 ou Etapa 10.',
        False,
        'ResultadoParidadeRenderizacaoOficial continua sendo entrada formal obrigatoria',
        'alto_se_inventario_for_usado_como_entrada_decisoria',
        'preservar_sem_autorizar_remocao_automatica',
        'Etapa 11 - preservacao',
        'Contrato da Etapa 11 exige ResultadoParidadeRenderizacaoOficial como entrada formal.',
        'A Etapa 11 apenas recebe inventário como evidência auxiliar não decisória.',
        'rota_oficial_preservada',
    ),
    _item(
        'PACOTE-OBS-TEMPORAL-MODULO-01',
        'nucleo/pacote_saida_observavel_temporal.py',
        'PacoteSaidaObservavelTemporal; construir_pacote_saida_observavel_temporal',
        'nucleo/saida_observavel_transitoria',
        'pacote_temporal_transitorio_removido',
        'Removido da rota operacional: a Situação Atual agora é montada por nucleo/situacao_atual_oficial.py antes da saída oficial.',
        False,
        'nucleo.situacao_atual_oficial.construir_situacao_atual_oficial',
        'baixo_apos_ME518B; alto_se_reintroduzido_na_rota_integrada',
        'preservar_remocao_e_nao_reintroduzir_pacote_temporal_como_canonico',
        'ME-518B concluida',
        'aplicacao/principal.py não importa nem chama o pacote temporal transitório.',
        'Arquivo removido por ausência de consumidor operacional restante; code/ permanece histórico preservado.',
        'legado_removido',
    ),
    _item(
        'SAIDA-OBS-CONSOLIDA-LOTES-01',
        'nucleo/saida_observavel.py',
        'construir_linhas_lotes_consolidados',
        'nucleo/renderizacao_observavel_legada',
        'helper_observavel_removido',
        'Removido da rota operacional; a consolidação necessária foi reimplementada com contrato oficial em nucleo/situacao_atual_oficial.py.',
        False,
        'nucleo.situacao_atual_oficial.construir_situacao_atual_oficial',
        'baixo_apos_ME518B; alto_se_reintroduzido_como_dependencia_da_rota_integrada',
        'preservar_remocao_e_nao_promover_helper_legado_a_canonico',
        'ME-518B concluida',
        'aplicacao/principal.py deixou de chamar helper legado de consolidação de lotes.',
        'Arquivo legado removido por ausência de consumidor operacional restante.',
        'legado_removido',
    ),
    _item(
        'SAIDA-OBS-AMOSTRAS-PAGAMENTOS-01',
        'nucleo/saida_observavel.py',
        'construir_amostras_pagamentos_operacionais',
        'nucleo/renderizacao_observavel_legada',
        'helper_console_fallback_removido',
        'Removido junto com nucleo/saida_observavel.py; amostras oficiais vêm de bloco_console do PacoteSaidaObservavelOficial.',
        False,
        'bloco_console.ultimos_pagamentos; bloco_console.pagamentos_data_referencia; bloco_console.proximos_pagamentos',
        'baixo_apos_ME518B; medio_se_reintroduzido_manual_fora_da_rota_integrada',
        'preservar_remocao_e_nao_reintroduzir_fallback_de_console',
        'ME-518B concluida',
        'Sem consumidor operacional restante em aplicacao/ ou nucleo/.',
        'Arquivo legado removido; code/ permanece histórico preservado.',
        'legado_removido',
    ),
    _item(
        'SAIDA-OBS-SITUACAO-ATUAL-HELPERS-01',
        'nucleo/saida_observavel.py',
        'construir_linhas_lotes_id_curta; construir_linhas_lotes_valores_curta; construir_resumo_patrimonio_total_lotes; construir_blocos_situacao_atual',
        'nucleo/renderizacao_observavel_legada',
        'helpers_situacao_atual_removidos',
        'Removidos da rota operacional; os blocos tabulares necessários foram reimplementados no contrato oficial de Situação Atual.',
        False,
        'nucleo.situacao_atual_oficial.construir_situacao_atual_oficial',
        'baixo_apos_ME518B; alto_se_reintroduzidos_como_dependencia_da_rota_integrada',
        'preservar_remocao_e_nao_promover_saida_observavel_legada_a_canonica',
        'ME-518B concluida',
        'aplicacao/principal.py deixou de importar/chamar helpers legados da Situação Atual.',
        'Arquivo legado removido por ausência de consumidor operacional restante.',
        'legado_removido',
    ),
    _item(
        'CONSOLE-STANDALONE-V17-S7-01',
        'aplicacao/console/principal.py',
        'main; render_console sem pacote oficial',
        'aplicacao/console',
        'fallback_console_standalone_removido',
        'Standalone não reconstrói mais V17/C7, matriz S7B ou integração S7C; falha explicitamente sem pacote oficial.',
        False,
        'aplicacao/principal.py com PacoteSaidaObservavelOficial preparado',
        'baixo_na_rota_oficial_apos_me518a; alto_se_reintroduzido',
        'preservar_falha_explicita_e_nao_reintroduzir_fallback',
        'ME-518A concluida para console',
        'main() do console chama render_console sem pacote apenas para produzir falha contratual explícita.',
        'Fallback executável foi removido da rota de console sem alterar decisão econômica.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'CONSOLE-SITUACAO-ANTIGA-01',
        'aplicacao/console/principal.py',
        'fallback antigo de Situação Atual',
        'aplicacao/console',
        'fallback_console_situacao_atual_removido',
        'Console renderiza Situação Atual exclusivamente a partir de bloco_console do PacoteSaidaObservavelOficial.',
        False,
        'bloco_console.situacao_atual_*',
        'baixo_na_rota_oficial_apos_me518a; alto_se_reintroduzido',
        'preservar_rota_oficial_sem_fallback',
        'ME-518A concluida para console',
        'Rota else antiga foi removida; ausência de pacote oficial gera erro explícito.',
        'A renderização observável não consulta mais helpers antigos para completar Situação Atual.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'CONSOLE-AMOSTRAS-FALLBACK-01',
        'aplicacao/console/principal.py',
        'fallback antigo de amostras de pagamentos',
        'aplicacao/console',
        'fallback_console_pagamentos_removido',
        'Console usa somente listas oficiais de pagamentos do bloco_console.',
        False,
        'bloco_console.ultimos_pagamentos; bloco_console.pagamentos_data_referencia; bloco_console.proximos_pagamentos',
        'baixo_na_rota_oficial_apos_me518a; medio_se_reintroduzido',
        'preservar_rota_oficial_sem_fallback',
        'ME-518A concluida para console',
        'Import e chamada do helper de amostras foram removidos do console.',
        'Amostras passam a ser renderização do pacote oficial, não reconstrução local.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'XLSX-FALLBACK-BLOQUEADO-01',
        'nucleo/gerar_planilha_operacional.py',
        'main; rotas de geração sem pacote oficial',
        'nucleo/xlsx',
        'fallback_xlsx_removido',
        'XLSX oficial recusa execução sem PacoteSaidaObservavelOficial preparado e abas oficiais completas.',
        False,
        'bloco_xlsx.abas e bloco_xlsx.situacao_atual_blocos',
        'baixo_na_rota_oficial_apos_me518a; alto_se_reintroduzido',
        'preservar_rota_xlsx_oficial_sem_fallback',
        'ME-518A concluida para XLSX',
        'Imports e chamadas de reconstrução temporal/observável foram removidos do gerador XLSX.',
        'Planilha oficial deixa de reconstruir conteúdo alternativo quando pacote oficial existe.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'SAIDA-CANONICA-V17-C7-01',
        'nucleo/construir_saida_canonica_v17_c7.py',
        'construir_saida_canonica_com_switching_v17_c7',
        'nucleo/saida_canonica_legada',
        'wrapper_legado_sem_consumidor_operacional',
        'Sem consumidor operacional na rota integrada; aplicacao/principal.py constrói SaidaCanonicaOficial a partir de ledger/gates/ranking e não chama este wrapper.',
        False,
        'nucleo.saida_canonica_oficial.construir_saida_canonica_oficial',
        'baixo_enquanto_nao_importado_pela_rota_integrada; alto_se_reintroduzido',
        'preservar_codigo_legado_sem_consumidor_operacional_e_nao_remover_automaticamente',
        'ME-518C concluida',
        'aplicacao/principal.py não importa nem chama o wrapper V17/C7; a Situação Atual recebe fonte observável derivada da SaidaCanonicaOficial preliminar.',
        'Substituído na rota integrada pela cadeia ResultadoMotorTemporalConjunto -> LedgerTemporalCanonico -> ResultadoGatesValidacaoNucleo -> SaidaCanonicaOficial -> PacoteSaidaObservavelOficial.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'MATRIZ-S7B-S7C-01',
        'nucleo/matriz_elegibilidade_fontes_s7b.py; nucleo/integracao_matriz_elegibilidade_pagamentos_s7c.py',
        'construir_matriz_elegibilidade_fontes_s7b; aplicar_matriz_elegibilidade_ao_fluxo_pagamentos_s7c',
        'nucleo/elegibilidade_legada_transitoria',
        'matriz_integracao_transitoria_sem_consumidor_operacional',
        'Sem consumidor operacional na rota integrada; aplicacao/principal.py não constrói matriz S7B nem aplica integração S7C ao fluxo de pagamentos.',
        False,
        'cadeia oficial motor/ledger/gates e obrigações cobertas no PacoteSaidaObservavelOficial',
        'baixo_enquanto_nao_importadas_pela_rota_integrada; alto_se_reintroduzidas',
        'preservar_codigo_legado_sem_consumidor_operacional_e_nao_remover_automaticamente',
        'ME-518C concluida',
        'aplicacao/principal.py não importa nem chama construir_matriz_elegibilidade_fontes_s7b ou aplicar_matriz_elegibilidade_ao_fluxo_pagamentos_s7c.',
        'A elegibilidade operacional consumida por console/XLSX passa pela cadeia oficial já validada; a matriz transitória permanece apenas como resíduo inventariado.',
        'legado_candidato_depreciacao',
    ),
    _item(
        'CODE-OTIMIZACAO-GASTOS-01',
        'code/otimizacao_gastos.py',
        'modulo code/otimizacao_gastos.py',
        'code/referencia_historica_fora_pipeline',
        'referencia_historica_preservada',
        'Referência histórica preservada integralmente fora do pipeline operacional atual.',
        False,
        'nao_aplicavel_por_preservacao_historica_integral',
        'alto_para_rastreabilidade_se_removido_ou_modificado; baixo_para_runtime_oficial_enquanto_nao_importado_pelo_pipeline',
        'preservar_integralmente_sem_mover_converter_substituir_ou_remover',
        'fora_do_pipeline_runtime_preservacao_historica',
        'ME-517 reclassificou code/ como referência histórica fora do pipeline.',
        'code/ permanece integralmente preservado e fora do escopo da ME-518C.',
        'historico_preservado',
    ),
    _item(
        'CODE-OTIMIZACAO-SWTICHING-01',
        'code/otimizacao_swtiching.py',
        'modulo code/otimizacao_swtiching.py',
        'code/referencia_historica_fora_pipeline',
        'referencia_historica_preservada',
        'Referência histórica de switching preservada integralmente fora do pipeline operacional atual; grafia swtiching preservada por ser nome de arquivo existente.',
        False,
        'nao_aplicavel_por_preservacao_historica_integral',
        'alto_para_rastreabilidade_se_removido_ou_modificado; baixo_para_runtime_oficial_enquanto_nao_importado_pelo_pipeline',
        'preservar_integralmente_sem_mover_converter_substituir_ou_remover',
        'fora_do_pipeline_runtime_preservacao_historica',
        'ME-517 reclassificou code/ como referência histórica fora do pipeline.',
        'code/ permanece integralmente preservado e fora do escopo da ME-518C.',
        'historico_preservado',
    ),
)


def listar_itens_inventario_legado_pipeline() -> list[dict[str, Any]]:
    return [item.como_dict() for item in ITENS_INVENTARIO_LEGADO_PIPELINE]


def construir_inventario_legado_pipeline() -> dict[str, Any]:
    return {
        'artefato': ARTEFATO_INVENTARIO_LEGADO_PIPELINE,
        'versao': VERSAO_INVENTARIO_LEGADO_PIPELINE,
        'fonte': FONTE_INVENTARIO,
        'natureza': 'evidencia_auxiliar_nao_decisoria',
        'estatico_declarativo_versionado': True,
        'usa_varredura_dinamica_filesystem': False,
        'entrada_formal_etapa11': 'ResultadoParidadeRenderizacaoOficial',
        'substitui_resultado_paridade_renderizacao_oficial': False,
        'remocao_automatica_autorizada': REMOCAO_AUTOMATICA_AUTORIZADA,
        'classificacoes_padronizadas': list(CLASSIFICACOES_PADRONIZADAS),
        'regras_contratuais': {
            'inventario_nao_decisorio': True,
            'nao_corrige_paridade': True,
            'nao_reabre_motor': True,
            'nao_reabre_ledger': True,
            'nao_reabre_gates': True,
            'nao_altera_etapa9': True,
            'nao_altera_etapa10': True,
            'nao_autoriza_remocao_automatica': True,
            'itens_com_dependencia_ativa_bloqueados_para_remocao': True,
            'me518a_console_xlsx_ja_concluida': True,
            'me518b_migracao_montagem_situacao_atual': True,
            'me518c_remocao_rota_integrada_v17_s7': True,
            'code_preservado_integralmente': True,
        },
        'itens': listar_itens_inventario_legado_pipeline(),
    }
