from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


VERSAO_INVENTARIO_LEGADO_PIPELINE = 'ME-516'
ARTEFATO_INVENTARIO_LEGADO_PIPELINE = 'InventarioLegadoPipeline'
FONTE_INVENTARIO = 'inventario_estatico_declarativo_versionado'
REMOCAO_AUTOMATICA_AUTORIZADA = False

CLASSIFICACOES_PADRONIZADAS = (
    'rota_oficial_preservada',
    'legado_candidato_depreciacao',
    'bloqueado_dependencia_ativa',
    'historico_preservado',
    'diagnostico_preservado_fora_pipeline',
    'fallback_temporario_bloqueado_para_remocao',
    'avaliacao_remocao_futura',
)


@dataclass(frozen=True, slots=True)
class ItemInventarioLegadoPipeline:
    identificador: str
    arquivo: str
    simbolo_funcao_classe: str
    camada: str
    tipo: str
    uso_atual: str
    dependencia_ativa: bool
    substituto_oficial: str
    risco_operacional: str
    decisao_recomendada: str
    etapa_alvo_tratamento: str
    evidencia: str
    justificativa_de_classificacao: str
    classificacao: str
    remocao_automatica_autorizada: bool = REMOCAO_AUTOMATICA_AUTORIZADA

    def como_dict(self) -> dict[str, Any]:
        return asdict(self)


ITENS_INVENTARIO_LEGADO_PIPELINE: tuple[ItemInventarioLegadoPipeline, ...] = (
    ItemInventarioLegadoPipeline(
        identificador='OFICIAL-PRINCIPAL-01',
        arquivo='aplicacao/principal.py',
        simbolo_funcao_classe='main; carregar_contexto_e_saida',
        camada='aplicacao',
        tipo='rota_oficial',
        uso_atual='Entrada operacional integrada que executa cadeia validada, console, XLSX, Etapa 10 e Etapa 11.',
        dependencia_ativa=False,
        substituto_oficial='nao_aplicavel_rota_oficial',
        risco_operacional='alto_se_removida_por_ser_ponto_de_entrada_oficial',
        decisao_recomendada='preservar_integralmente',
        etapa_alvo_tratamento='Etapa 11 - preservacao',
        evidencia='aplicacao/principal.py chama Etapas oficiais e permanece como ponto de entrada operacional.',
        justificativa_de_classificacao='Rota oficial não é resíduo; deve ser registrada para separar preservação oficial de legado executável.',
        classificacao='rota_oficial_preservada',
    ),
    ItemInventarioLegadoPipeline(
        identificador='OFICIAL-SAIDA-OBSERVAVEL-09-01',
        arquivo='nucleo/saida_observavel_oficial.py',
        simbolo_funcao_classe='construir_pacote_saida_observavel_oficial',
        camada='nucleo/saida_oficial',
        tipo='pacote_oficial_etapa9',
        uso_atual='Materializa PacoteSaidaObservavelOficial consumido por console, XLSX e Etapa 10.',
        dependencia_ativa=False,
        substituto_oficial='nao_aplicavel_rota_oficial',
        risco_operacional='alto_se_confundido_com_pacote_temporal_legado',
        decisao_recomendada='preservar_como_substituto_oficial_dos_helpers_observaveis_antigos',
        etapa_alvo_tratamento='Etapa 9 - preservacao',
        evidencia='Pacote oficial é entrada da paridade forte da Etapa 10.',
        justificativa_de_classificacao='É o substituto oficial contra o qual resíduos observáveis devem ser comparados, sem substituição pela Etapa 11.',
        classificacao='rota_oficial_preservada',
    ),
    ItemInventarioLegadoPipeline(
        identificador='OFICIAL-ETAPA11-01',
        arquivo='nucleo/limpeza_depreciacao_controlada.py',
        simbolo_funcao_classe='construir_resultado_limpeza_depreciacao_controlada',
        camada='nucleo/governanca',
        tipo='etapa_governanca_nao_decisoria',
        uso_atual='Classifica evidências auxiliares sem reabrir motor, ledger, gates, Etapa 9 ou Etapa 10.',
        dependencia_ativa=False,
        substituto_oficial='ResultadoParidadeRenderizacaoOficial continua sendo entrada formal obrigatoria',
        risco_operacional='alto_se_inventario_for_usado_como_entrada_decisoria',
        decisao_recomendada='preservar_sem_autorizar_remocao_automatica',
        etapa_alvo_tratamento='Etapa 11 - preservacao',
        evidencia='Contrato da Etapa 11 exige ResultadoParidadeRenderizacaoOficial como entrada formal.',
        justificativa_de_classificacao='A Etapa 11 apenas recebe inventário como evidência auxiliar não decisória.',
        classificacao='rota_oficial_preservada',
    ),
    ItemInventarioLegadoPipeline(
        identificador='PACOTE-OBS-TEMPORAL-MODULO-01',
        arquivo='nucleo/pacote_saida_observavel_temporal.py',
        simbolo_funcao_classe='PacoteSaidaObservavelTemporal',
        camada='nucleo/saida_observavel_transitoria',
        tipo='pacote_temporal_transitorio',
        uso_atual='Ainda fornece saldos de replay, pagamentos por chave, valores sacados, aplicações, produtos e lotes observáveis para rotas ricas.',
        dependencia_ativa=True,
        substituto_oficial='PacoteSaidaObservavelOficial, quando todos os blocos ricos estiverem materializados oficialmente',
        risco_operacional='alto_se_removido_antes_da_migracao_dos_blocos_ricos_para_a_cadeia_oficial',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migracao/remocao controlada',
        evidencia='Modulo é importado por aplicacao/principal.py, aplicacao/console/principal.py e nucleo/gerar_planilha_operacional.py.',
        justificativa_de_classificacao='É fallback temporal ativo; inventariar não permite depreciar enquanto houver dependência executável.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='PACOTE-OBS-TEMPORAL-CONSTRUTOR-01',
        arquivo='nucleo/pacote_saida_observavel_temporal.py',
        simbolo_funcao_classe='construir_pacote_saida_observavel_temporal',
        camada='nucleo/saida_observavel_transitoria',
        tipo='construtor_fallback_temporal',
        uso_atual='Constrói pacote temporal a partir de contexto, saída e snapshots observáveis para Situação Atual rica.',
        dependencia_ativa=True,
        substituto_oficial='construir_pacote_saida_observavel_oficial',
        risco_operacional='alto_por_compor_dados_observaveis_consumidos_por_console_e_xlsx_em_rotas_de_compatibilidade',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de substituicao por blocos oficiais',
        evidencia='Contém evidência usa_fallback_canonico_bruto e metadados etapa5_pode_abrir_agora=False.',
        justificativa_de_classificacao='O construtor ainda é chamado explicitamente; sua classificação segura é bloqueio temporário.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-OBS-CONSOLIDA-LOTES-01',
        arquivo='nucleo/saida_observavel.py',
        simbolo_funcao_classe='construir_linhas_lotes_consolidados',
        camada='nucleo/renderizacao_observavel_legada',
        tipo='helper_observavel_ativo',
        uso_atual='Consolida lotes ativos/exauridos e ainda atende bootstrap de pacote temporal e Situação Atual rica.',
        dependencia_ativa=True,
        substituto_oficial='Blocos de lotes do PacoteSaidaObservavelOficial',
        risco_operacional='alto_por_afetar_patrimonio_lotes_e_dimensoes_da_Situacao_Atual',
        decisao_recomendada='bloquear_remocao_e_migrar_em_frente_posterior',
        etapa_alvo_tratamento='ME posterior de migracao da Situação Atual rica',
        evidencia='Chamado por aplicacao/principal.py e aplicacao/console/principal.py para bootstrap e fallback.',
        justificativa_de_classificacao='Apesar de legado, tem dependência ativa; não pode ser candidato removível automático.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-OBS-AMOSTRAS-PAGAMENTOS-01',
        arquivo='nucleo/saida_observavel.py',
        simbolo_funcao_classe='construir_amostras_pagamentos_operacionais',
        camada='nucleo/renderizacao_observavel_legada',
        tipo='helper_console_fallback',
        uso_atual='Ainda alimenta amostras de pagamentos na rota de console sem pacote oficial preparado.',
        dependencia_ativa=True,
        substituto_oficial='bloco_console.obrigacoes_cobertas e bloco_console.proximos_pagamentos do PacoteSaidaObservavelOficial',
        risco_operacional='medio_alto_por_afetar_console_standalone_e_amostras_operacionais',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migracao do console standalone',
        evidencia='Importado e chamado por aplicacao/console/principal.py.',
        justificativa_de_classificacao='É fallback de console ativo; remoção depende de migração completa do standalone.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-OBS-LOTES-ID-CURTA-01',
        arquivo='nucleo/saida_observavel.py',
        simbolo_funcao_classe='construir_linhas_lotes_id_curta',
        camada='nucleo/renderizacao_observavel_legada',
        tipo='helper_situacao_atual',
        uso_atual='Gera tabelas curtas de identificação de lotes para console e blocos ricos de Situação Atual.',
        dependencia_ativa=True,
        substituto_oficial='situacao_atual_lotes_*_id do PacoteSaidaObservavelOficial',
        risco_operacional='alto_por_afetar_dimensao_e_conteudo_da_Situacao_Atual',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migração da Situação Atual',
        evidencia='Chamado por construir_blocos_situacao_atual e por _render_situacao_atual_operacional.',
        justificativa_de_classificacao='Dependência ativa observável; inventário registra bloqueio, não depreciação.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-OBS-LOTES-VALORES-CURTA-01',
        arquivo='nucleo/saida_observavel.py',
        simbolo_funcao_classe='construir_linhas_lotes_valores_curta',
        camada='nucleo/renderizacao_observavel_legada',
        tipo='helper_situacao_atual',
        uso_atual='Gera tabelas curtas de valores de lotes para console e blocos ricos de Situação Atual.',
        dependencia_ativa=True,
        substituto_oficial='situacao_atual_lotes_*_valores do PacoteSaidaObservavelOficial',
        risco_operacional='alto_por_afetar_patrimonio_liquido_e_rendimento_observavel',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migração da Situação Atual',
        evidencia='Chamado por construir_blocos_situacao_atual e por _render_situacao_atual_operacional.',
        justificativa_de_classificacao='Dependência ativa observável; não há autorização de remoção.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-OBS-PATRIMONIO-TOTAL-01',
        arquivo='nucleo/saida_observavel.py',
        simbolo_funcao_classe='construir_resumo_patrimonio_total_lotes',
        camada='nucleo/renderizacao_observavel_legada',
        tipo='helper_patrimonial_observavel',
        uso_atual='Calcula resumo observável de patrimônio e rendimento dos lotes para Situação Atual.',
        dependencia_ativa=True,
        substituto_oficial='situacao_atual_patrimonio_total do PacoteSaidaObservavelOficial',
        risco_operacional='alto_por_ser_sensivel_aos_valores_97299_50_e_1231_34_no_console',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migração patrimonial observável',
        evidencia='Usado para materializar Patrimônio líquido atual e Rendimento líquido atual em rotas de Situação Atual.',
        justificativa_de_classificacao='Função ainda participa de saída observável validada; remoção seria alteração funcional.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-OBS-DIAS-FALLBACK-01',
        arquivo='nucleo/saida_observavel.py',
        simbolo_funcao_classe='_calcular_dias_observavel',
        camada='nucleo/renderizacao_observavel_legada',
        tipo='fallback_renderizacao_dias',
        uso_atual='Calcula dias corridos/úteis observáveis se o cálculo canônico falhar na camada de renderização.',
        dependencia_ativa=True,
        substituto_oficial='nucleo.calendario_financeiro.calcular_dias_lote',
        risco_operacional='medio_por_ser_fallback_nao_decisorio_mas_sensivel_a_colunas_de_lotes',
        decisao_recomendada='bloquear_remocao_ate_auditoria_especifica',
        etapa_alvo_tratamento='ME posterior de limpeza de fallback observável',
        evidencia='Comentário no código declara fallback apenas observável para não quebrar renderização.',
        justificativa_de_classificacao='Fallback explícito ainda importável; não deve ser mascarado nem removido nesta ME.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='CONSOLE-STANDALONE-V17-S7-01',
        arquivo='aplicacao/console/principal.py',
        simbolo_funcao_classe='main; render_console sem pacote oficial',
        camada='aplicacao/console',
        tipo='fallback_console_standalone',
        uso_atual='Quando executado isoladamente, ainda reconstrói saída V17/C7, matriz S7B e integração S7C.',
        dependencia_ativa=True,
        substituto_oficial='aplicacao/principal.py com PacoteSaidaObservavelOficial',
        risco_operacional='alto_por_reabrir_rota_standalone_legada_se_removido_sem_migracao',
        decisao_recomendada='bloquear_remocao_e_planejar_migracao_do_standalone',
        etapa_alvo_tratamento='ME posterior de console standalone oficial',
        evidencia='main() do console chama construir_saida_canonica_com_switching_v17_c7 e aplicar_matriz_elegibilidade_ao_fluxo_pagamentos_s7c.',
        justificativa_de_classificacao='Fallback ativo de console; inventário deve torná-lo explícito sem removê-lo.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='CONSOLE-SITUACAO-ANTIGA-01',
        arquivo='aplicacao/console/principal.py',
        simbolo_funcao_classe='_render_situacao_atual_operacional',
        camada='aplicacao/console',
        tipo='fallback_console_situacao_atual',
        uso_atual='Renderiza Situação Atual por helpers antigos quando pacote oficial completo não está disponível.',
        dependencia_ativa=True,
        substituto_oficial='_render_situacao_atual_oficial_minima com bloco_console completo',
        risco_operacional='alto_por_afetar_Situacao_Atual_A1_M134_e_totais_do_console',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de remoção de fallback de Situação Atual',
        evidencia='render_console escolhe esta rota no else de pacote_oficial_preparado e _situacao_atual_oficial_completa.',
        justificativa_de_classificacao='A rota consulta saída/contexto para completar renderização quando pacote oficial está ausente ou incompleto.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='CONSOLE-AMOSTRAS-FALLBACK-01',
        arquivo='aplicacao/console/principal.py',
        simbolo_funcao_classe='_render_amostras_pagamentos_operacionais',
        camada='aplicacao/console',
        tipo='fallback_console_pagamentos',
        uso_atual='Renderiza amostras operacionais a partir da saída canônica antiga quando pacote oficial não está preparado.',
        dependencia_ativa=True,
        substituto_oficial='_render_amostras_pagamentos_operacionais_oficiais',
        risco_operacional='medio_alto_por_afetar_amostras_de_ultimos_e_proximos_pagamentos',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de console oficial standalone',
        evidencia='render_console chama fallback quando pacote_oficial_preparado é falso.',
        justificativa_de_classificacao='Fallback de console preservado temporariamente; não decisório para Etapa 11.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='XLSX-FALLBACK-BLOQUEADO-01',
        arquivo='nucleo/gerar_planilha_operacional.py',
        simbolo_funcao_classe='main; rotas de geração sem pacote oficial',
        camada='nucleo/xlsx',
        tipo='fallback_xlsx_bloqueado',
        uso_atual='Mantém proteções e compatibilidades para geração de planilha operacional sem promover artefatos diagnósticos.',
        dependencia_ativa=True,
        substituto_oficial='geração XLSX baseada em PacoteSaidaObservavelOficial',
        risco_operacional='alto_por_afetar_abas_Extrato_Passado_Extrato_Futuro_Switching_Carteira_Situacao_Atual',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de limpeza da geração XLSX legada',
        evidencia='Módulo ainda importa pacote temporal e helpers de saida_observavel.',
        justificativa_de_classificacao='A ME-516 não pode alterar XLSX nem fallback legado; apenas inventaria sua existência.',
        classificacao='fallback_temporario_bloqueado_para_remocao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='XLSX-DIAGNOSTICO-U7-FIFO-01',
        arquivo='nucleo/gerar_planilha_operacional.py',
        simbolo_funcao_classe='_adicionar_aba_tabela_operacional_pagamentos; _adicionar_abas_saida_operacional_pagamentos_u7',
        camada='nucleo/xlsx_diagnostico',
        tipo='artefato_diagnostico',
        uso_atual='Funções diagnósticas U7/FIFO permanecem importáveis, mas não devem ser fonte econômica oficial.',
        dependencia_ativa=False,
        substituto_oficial='abas oficiais derivadas de PacoteSaidaObservavelOficial',
        risco_operacional='medio_se_promovidas_indevidamente_como_saida_oficial',
        decisao_recomendada='preservar_fora_pipeline_oficial_ate_politica_documental',
        etapa_alvo_tratamento='ME posterior de limpeza documental/diagnóstica',
        evidencia='Funções leem CSVs de saidas/diagnostico e criam abas diagnósticas condicionais.',
        justificativa_de_classificacao='Diagnóstico deve ser preservado fora do pipeline oficial, sem remoção automática.',
        classificacao='diagnostico_preservado_fora_pipeline',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-CANONICA-V17-C7-01',
        arquivo='nucleo/construir_saida_canonica_v17_c7.py',
        simbolo_funcao_classe='construir_saida_canonica_com_switching_v17_c7',
        camada='nucleo/saida_canonica_legada',
        tipo='wrapper_legado_ativo',
        uso_atual='Ainda é usado por principal.py e console standalone para construir saída canônica antiga antes da saída oficial.',
        dependencia_ativa=True,
        substituto_oficial='nucleo.saida_canonica_oficial.construir_saida_canonica_oficial',
        risco_operacional='alto_se_removido_antes_de_migrar_fontes_de_saida_canonica_antiga',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de substituição da saída canônica V17',
        evidencia='Importado por aplicacao/principal.py, aplicacao/console/principal.py e gerar_planilha_operacional.py.',
        justificativa_de_classificacao='Apesar de legado, possui dependência ativa direta no runtime atual.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='SAIDA-CANONICA-ANTIGA-01',
        arquivo='nucleo/saida_canonica.py',
        simbolo_funcao_classe='PacoteSaidaCanonica',
        camada='nucleo/saida_canonica_legada',
        tipo='modelo_saida_antigo',
        uso_atual='Modelo antigo ainda pode ser retornado por wrappers e consumidores transitórios.',
        dependencia_ativa=True,
        substituto_oficial='PacoteSaidaCanonicaOficial',
        risco_operacional='alto_por_ser_modelo_de_dados_com_consumidores_potenciais',
        decisao_recomendada='bloquear_remocao_ate_prova_de_ausencia_de_consumidores',
        etapa_alvo_tratamento='ME posterior de inventário de consumidores',
        evidencia='Relatório documental anterior apontou dependência transitória e alto risco.',
        justificativa_de_classificacao='Sem prova segura de desuso, classificar como dependência ativa bloqueada.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='MATRIZ-S7B-01',
        arquivo='nucleo/matriz_elegibilidade_fontes_s7b.py',
        simbolo_funcao_classe='construir_matriz_elegibilidade_fontes_s7b',
        camada='nucleo/elegibilidade_legada_transitoria',
        tipo='matriz_transitoria_ativa',
        uso_atual='Ainda é chamada para aplicar elegibilidade sobre saída canônica antiga em principal e console standalone.',
        dependencia_ativa=True,
        substituto_oficial='cadeia oficial motor/ledger/gates já validada antes da renderização',
        risco_operacional='alto_se_removida_sem_substituir_fluxo_transitorio',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migração de elegibilidade transitória',
        evidencia='Importada e chamada por aplicacao/principal.py e aplicacao/console/principal.py.',
        justificativa_de_classificacao='Matriz transitória ativa; não pode ser depreciada nesta ME.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='INTEGRACAO-S7C-01',
        arquivo='nucleo/integracao_matriz_elegibilidade_pagamentos_s7c.py',
        simbolo_funcao_classe='aplicar_matriz_elegibilidade_ao_fluxo_pagamentos_s7c',
        camada='nucleo/elegibilidade_legada_transitoria',
        tipo='integracao_transitoria_ativa',
        uso_atual='Ainda aplica matriz S7C ao fluxo de pagamentos da saída canônica antiga.',
        dependencia_ativa=True,
        substituto_oficial='cadeia oficial de obrigações cobertas no PacoteSaidaObservavelOficial',
        risco_operacional='alto_se_removida_sem_migrar_consumidores',
        decisao_recomendada='bloquear_remocao_nesta_etapa',
        etapa_alvo_tratamento='ME posterior de migração de integração transitória',
        evidencia='Chamada logo após construir_matriz_elegibilidade_fontes_s7b.',
        justificativa_de_classificacao='Integração ativa e transitória; inventário não autoriza remoção.',
        classificacao='bloqueado_dependencia_ativa',
    ),
    ItemInventarioLegadoPipeline(
        identificador='CODE-OTIMIZACAO-GASTOS-01',
        arquivo='code/otimizacao_gastos.py',
        simbolo_funcao_classe='modulo code/otimizacao_gastos.py',
        camada='code/legado_executavel',
        tipo='modulo_antigo',
        uso_atual='Módulo antigo em code/ relacionado à otimização de gastos; não deve ser usado como fonte decisória nesta ME.',
        dependencia_ativa=False,
        substituto_oficial='pipeline oficial em aplicacao/principal.py e nucleo oficial validado',
        risco_operacional='medio_se_importado_manual_ou_confundido_com_rota_oficial',
        decisao_recomendada='avaliar_depreciacao_futura_sem_remocao_automatica',
        etapa_alvo_tratamento='ME posterior de limpeza de code legado',
        evidencia='Arquivo code/otimizacao_gastos.py ainda existe/importável no repositório.',
        justificativa_de_classificacao='Sem prova de dependência runtime, mas por segurança fica como candidato futuro, não removível automático.',
        classificacao='legado_candidato_depreciacao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='CODE-OTIMIZACAO-SWTICHING-01',
        arquivo='code/otimizacao_swtiching.py',
        simbolo_funcao_classe='modulo code/otimizacao_swtiching.py',
        camada='code/legado_executavel',
        tipo='modulo_antigo',
        uso_atual='Módulo antigo em code/ relacionado a switching; grafia swtiching preservada por ser nome de arquivo existente.',
        dependencia_ativa=False,
        substituto_oficial='rotas oficiais de switching auditadas no pacote oficial e Etapa 10',
        risco_operacional='medio_se_confundido_com_switching_oficial',
        decisao_recomendada='avaliar_depreciacao_futura_sem_remocao_automatica',
        etapa_alvo_tratamento='ME posterior de limpeza de code legado',
        evidencia='Arquivo code/otimizacao_swtiching.py ainda existe/importável no repositório.',
        justificativa_de_classificacao='Legado candidato, mas não removível automaticamente pela ME-516.',
        classificacao='legado_candidato_depreciacao',
    ),
    ItemInventarioLegadoPipeline(
        identificador='LOGS-ITERACOES-LEGADOS-01',
        arquivo='logs/iteracoes/*.md',
        simbolo_funcao_classe='historico_documental_microetapas',
        camada='documentacao/historico',
        tipo='historico_auditavel',
        uso_atual='Preserva decisões, auditorias e contexto técnico das microetapas antigas.',
        dependencia_ativa=False,
        substituto_oficial='politica_documental_futura',
        risco_operacional='baixo_no_runtime_alto_para_rastreabilidade_se_removido',
        decisao_recomendada='preservar_como_historico',
        etapa_alvo_tratamento='fora_do_pipeline_runtime',
        evidencia='Relatórios e logs históricos registram evolução V17/S7/U7/FIFO e auditorias anteriores.',
        justificativa_de_classificacao='Histórico não deve ser tratado como código removível nesta etapa.',
        classificacao='historico_preservado',
    ),
    ItemInventarioLegadoPipeline(
        identificador='RELATORIO-INVENTARIO-ANTERIOR-01',
        arquivo='relatorios/principais/inventarios/INVENTARIO_RESIDUOS_LEGADOS_ETAPA11.md',
        simbolo_funcao_classe='inventario_documental_anterior',
        camada='documentacao/inventario',
        tipo='diagnostico_historico',
        uso_atual='Documento de inventário anterior permanece como evidência histórica, mas não é entrada runtime estruturada.',
        dependencia_ativa=False,
        substituto_oficial='nucleo/inventario_legado_pipeline.py',
        risco_operacional='baixo_se_preservado_como_historico; medio_se_usado_como_input_decisorio',
        decisao_recomendada='preservar_fora_pipeline_como_historico',
        etapa_alvo_tratamento='fora_do_pipeline_runtime',
        evidencia='O próprio documento declara pendência de transformar inventário documental em entrada operacional.',
        justificativa_de_classificacao='Após ME-516, o módulo estruturado substitui o markdown como evidência consumível pela Etapa 11.',
        classificacao='diagnostico_preservado_fora_pipeline',
    ),
)


def listar_itens_inventario_legado_pipeline() -> list[dict[str, Any]]:
    return [item.como_dict() for item in ITENS_INVENTARIO_LEGADO_PIPELINE]


def construir_inventario_legado_pipeline() -> dict[str, Any]:
    return {
        'artefato': ARTEFATO_INVENTARIO_LEGADO_PIPELINE,
        'versao': VERSAO_INVENTARIO_LEGADO_PIPELINE,
        'fonte': FONTE_INVENTARIO,
        'natureza': 'evidencia_auxiliar_nao_decisoria',
        'estatico_declarativo_versionado': True,
        'usa_varredura_dinamica_filesystem': False,
        'entrada_formal_etapa11': 'ResultadoParidadeRenderizacaoOficial',
        'substitui_resultado_paridade_renderizacao_oficial': False,
        'remocao_automatica_autorizada': REMOCAO_AUTOMATICA_AUTORIZADA,
        'classificacoes_padronizadas': list(CLASSIFICACOES_PADRONIZADAS),
        'regras_contratuais': {
            'inventario_nao_decisorio': True,
            'nao_corrige_paridade': True,
            'nao_reabre_motor': True,
            'nao_reabre_ledger': True,
            'nao_reabre_gates': True,
            'nao_altera_etapa9': True,
            'nao_altera_etapa10': True,
            'nao_autoriza_remocao_automatica': True,
            'itens_com_dependencia_ativa_bloqueados_para_remocao': True,
        },
        'itens': listar_itens_inventario_legado_pipeline(),
    }
